language: node_js
node_js:
  - 11.6.0
cache: npm
install:
  - npm ci

script:
  - gulp run 

deploy:
  provider: pages
  target_branch: dev
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  keep_history: true
  on:
    branch: migration-to-ci
